### ISSUE TITLE
How to mark selected in catalog.json

### ISSUE THREAD

**Issue by fkhjoy** [dbt-labs/tap-amazon-advertising#1]
Hi !
Could you please tell me how I can mark selected?
I couldn't find any option in the json.
Thank You.
![Screenshot from 2021-02-17 19-27-32](https://user-images.githubusercontent.com/25137428/108211130-8c4e4d00-7156-11eb-9b4e-69af1b1d229a.png)

**Comment by drewbanin** [comment]
hey there - we no longer actively maintain this repo, but did want to help out here :)

```
#!/usr/bin/env python
import sys
import json
import subprocess
from collections import OrderedDict


output = subprocess.check_output(['tap-amazon-advertising', '-d', '-c', 'config.json'])
schema = json.loads(output.decode("utf-8"), object_pairs_hook=OrderedDict)
streams = schema["streams"]
for s in streams:
    s["schema"]["selected"] = True
    s["metadata"][0]["metadata"]["selected"] = True

json.dump(schema, fp=sys.stdout, indent=2)
```

Try sticking this code in a file called `get_catalog.py` and then run `python get_catalog.py > catalog.json`

**Comment by fkhjoy** [comment]
> hey there - we no longer actively maintain this repo, but did want to help out here :)
> 
> ```
> #!/usr/bin/env python
> import sys
> import json
> import subprocess
> from collections import OrderedDict
> 
> 
> output = subprocess.check_output(['tap-amazon-advertising', '-d', '-c', 'config.json'])
> schema = json.loads(output.decode("utf-8"), object_pairs_hook=OrderedDict)
> streams = schema["streams"]
> for s in streams:
>     s["schema"]["selected"] = True
>     s["metadata"][0]["metadata"]["selected"] = True
> 
> json.dump(schema, fp=sys.stdout, indent=2)
> ```
> 
> Try sticking this code in a file called `get_catalog.py` and then run `python get_catalog.py > catalog.json`

Thank You for your help.
Is there any up to date repo for advertising api?
I also noticed tap-amazon-ads-dsp. What about that?

**Comment by drewbanin** [comment]
I think you might have more luck inquiring over here: https://github.com/singer-io/tap-amazon-ads-dsp

This tap was not written by Fishtown Analytics and I regret that we are unable to assist with it!

**Comment by fkhjoy** [comment]
After running that code. I am getting error like below. I code add "selected" = true in metadata and schema...
But I got another error which is "this amazon id doesn't have advertising account" or similar. I used security profile id for that which format is `amzn1.application.deXXXXXXXXXXXXXXX`.
Is that right?
N.B. I could get the refresh token using the same config but I was thinking the profile id is mistaken.
<details>
<summary>ERROR:</summary>

```

CRITICAL (unauthorized_client) Not authorized for requested operation
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/tap-amazon-advertising", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/singer/utils.py", line 192, in wrapped
    return fnc(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tap_amazon_advertising/__init__.py", line 23, in main
    client = AmazonAdvertisingClient(args.config)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tap_amazon_advertising/client.py", line 22, in __init__
    self.access_token = self.get_authorization()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tap_amazon_advertising/client.py", line 31, in get_authorization
    tokens = oauth.refresh_token(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError: (unauthorized_client) Not authorized for requested operation
Traceback (most recent call last):
  File "get_catalog.py", line 8, in <module>
    output = subprocess.check_output(['tap-amazon-advertising', '-d', '-c', 'config.json'])
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tap-amazon-advertising', '-d', '-c', 'config.json']' returned non-zero exit status 1.
ubuntu@fkhjoy:~/Tasks/Python/spotify/tap-amazon-advertising-master$ python get_catalog.py > catalog.json
CRITICAL (unauthorized_client) Not authorized for requested operation
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/tap-amazon-advertising", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/singer/utils.py", line 192, in wrapped
    return fnc(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tap_amazon_advertising/__init__.py", line 23, in main
    client = AmazonAdvertisingClient(args.config)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tap_amazon_advertising/client.py", line 22, in __init__
    self.access_token = self.get_authorization()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tap_amazon_advertising/client.py", line 31, in get_authorization
    tokens = oauth.refresh_token(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/requests_oauthlib/oauth2_session.py", line 309, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/lib/python3/dist-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.UnauthorizedClientError: (unauthorized_client) Not authorized for requested operation
Traceback (most recent call last):
  File "get_catalog.py", line 8, in <module>
    output = subprocess.check_output(['tap-amazon-advertising', '-d', '-c', 'config.json'])
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['tap-amazon-advertising', '-d', '-c', 'config.json']' returned non-zero exit status 1

```

</details>
